version: "3.9"

services:
  rust-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app             # монтируем код
      - cargo-target:/usr/src/app/target  # кэш сборки
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    stdin_open: true
    tty: true
    depends_on:
      rabbit_mq:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  rabbit_mq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7
    volumes:
      - redis-data:/data

volumes:
  cargo-target:
  mysql-data:
  rabbitmq-data:
  redis-data:
