//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod digest_subscriptions;
pub mod health_pings;
pub mod notification_log;
pub mod pending_notifications;
pub mod pr_reviews;
pub mod release_plan_repositories;
pub mod release_plans;
pub mod repositories;
pub mod repository_pull_requests;
pub mod repository_task_tracker;
pub mod roles;
pub mod user_connection_repositories;
pub mod user_has_roles;
pub mod user_notifications;
pub mod user_preferences;
pub mod user_social_accounts;
pub mod user_version_control_accounts;
pub mod users;
