//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pr_reviews")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub repo: String,
    pub pr_number: i32,
    pub reviewer_login: String,
    pub last_reviewed_at: DateTimeUtc,
    pub last_review_state: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
