//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

// pub use super::git_hub_accounts as GitHubAccounts;
// pub use super::repositories as Repositories;
// pub use super::repository_settings as RepositorySettings;
// pub use super::repository_users as RepositoryUsers;
// pub use super::roles as Roles;
// pub use super::user_roles as UserRoles;
pub use super::telegram_accounts as TelegramAccounts;
pub use super::users as Users;
