//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "release_plans")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub planned_date: Date,
    pub call_datetime: Option<DateTimeUtc>,
    pub meeting_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    pub status: String,
    pub announce_chat_id: Option<i64>,
    pub notified24h_at: Option<DateTimeUtc>,
    pub notified_call_at: Option<DateTimeUtc>,
    pub notified_release_day_at: Option<DateTimeUtc>,
    pub created_by_user_id: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::release_plan_repositories::Entity")]
    ReleasePlanRepositories,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedByUserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::release_plan_repositories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleasePlanRepositories.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::repositories::Entity> for Entity {
    fn to() -> RelationDef {
        super::release_plan_repositories::Relation::Repositories.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::release_plan_repositories::Relation::ReleasePlans
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
