//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "release_plan_repositories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub release_plan_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub repository_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::release_plans::Entity",
        from = "Column::ReleasePlanId",
        to = "super::release_plans::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ReleasePlans,
    #[sea_orm(
        belongs_to = "super::repositories::Entity",
        from = "Column::RepositoryId",
        to = "super::repositories::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Repositories,
}

impl Related<super::release_plans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleasePlans.def()
    }
}

impl Related<super::repositories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Repositories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
