//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "repository_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub repository_id: i32,
    pub task_tracker_api_token: String,
    pub task_tracker_base: String,
    pub task_tracker_space_id: i64,
    pub task_tracker_qa_column_id: i64,
    pub task_tracker_regexp: String,
    pub task_tracker_path_to_card: String,
    pub telegram_chat_id: i64,
    pub git_hub_webhook_secret: String,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::repositories::Entity",
        from = "Column::RepositoryId",
        to = "super::repositories::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Repositories,
}

impl Related<super::repositories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Repositories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
