//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "repositories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub git_hub_repo_id: i64,
    pub owner: String,
    pub name: String,
    pub is_active: i8,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::repository_settings::Entity")]
    RepositorySettings,
    #[sea_orm(has_many = "super::repository_users::Entity")]
    RepositoryUsers,
}

impl Related<super::repository_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RepositorySettings.def()
    }
}

impl Related<super::repository_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RepositoryUsers.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::repository_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::repository_users::Relation::Repositories.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
