//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub is_active: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_has_roles::Entity")]
    UserHasRoles,
    #[sea_orm(has_many = "super::user_socials_services::Entity")]
    UserSocialsServices,
    #[sea_orm(has_many = "super::user_version_control_services::Entity")]
    UserVersionControlServices,
}

impl Related<super::user_has_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserHasRoles.def()
    }
}

impl Related<super::user_socials_services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSocialsServices.def()
    }
}

impl Related<super::user_version_control_services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserVersionControlServices.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_has_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_has_roles::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
