//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub is_active: bool,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::git_hub_accounts::Entity")]
    GitHubAccounts,
    #[sea_orm(has_many = "super::repository_users::Entity")]
    RepositoryUsers,
    #[sea_orm(has_many = "super::telegram_accounts::Entity")]
    TelegramAccounts,
    #[sea_orm(has_many = "super::user_roles::Entity")]
    UserRoles,
}

impl Related<super::git_hub_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GitHubAccounts.def()
    }
}

impl Related<super::repository_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RepositoryUsers.def()
    }
}

impl Related<super::telegram_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramAccounts.def()
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl Related<super::repositories::Entity> for Entity {
    fn to() -> RelationDef {
        super::repository_users::Relation::Repositories.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::repository_users::Relation::Users.def().rev())
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_roles::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
