//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub is_active: i8,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::digest_subscriptions::Entity")]
    DigestSubscriptions,
    #[sea_orm(has_many = "super::notification_log::Entity")]
    NotificationLog,
    #[sea_orm(has_many = "super::pending_notifications::Entity")]
    PendingNotifications,
    #[sea_orm(has_many = "super::release_plans::Entity")]
    ReleasePlans,
    #[sea_orm(has_many = "super::user_connection_repositories::Entity")]
    UserConnectionRepositories,
    #[sea_orm(has_many = "super::user_has_roles::Entity")]
    UserHasRoles,
    #[sea_orm(has_many = "super::user_notifications::Entity")]
    UserNotifications,
    #[sea_orm(has_one = "super::user_preferences::Entity")]
    UserPreferences,
    #[sea_orm(has_many = "super::user_social_accounts::Entity")]
    UserSocialAccounts,
    #[sea_orm(has_many = "super::user_version_control_accounts::Entity")]
    UserVersionControlAccounts,
}

impl Related<super::digest_subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DigestSubscriptions.def()
    }
}

impl Related<super::notification_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationLog.def()
    }
}

impl Related<super::pending_notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PendingNotifications.def()
    }
}

impl Related<super::release_plans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleasePlans.def()
    }
}

impl Related<super::user_connection_repositories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserConnectionRepositories.def()
    }
}

impl Related<super::user_has_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserHasRoles.def()
    }
}

impl Related<super::user_notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserNotifications.def()
    }
}

impl Related<super::user_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPreferences.def()
    }
}

impl Related<super::user_social_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSocialAccounts.def()
    }
}

impl Related<super::user_version_control_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserVersionControlAccounts.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_has_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_has_roles::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
