use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(UserVersionControlServices::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(UserVersionControlServices::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::UserId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::VersionControlType)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::VersionControlUserId)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::VersionControlLogin)
                            .string_len(255)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::VersionControlEmail)
                            .string_len(255)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::VersionControlAvatarUrl)
                            .string_len(512)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::AccessToken)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::RefreshToken)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::TokenType)
                            .string_len(32)
                            .default("Bearer"),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::ExpiresAt)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::Scope)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::CreatedAt)
                            .timestamp_with_time_zone()
                            .default(SimpleExpr::Keyword(Keyword::CurrentTimestamp))
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(UserVersionControlServices::UpdatedAt)
                            .timestamp_with_time_zone()
                            .default(SimpleExpr::Keyword(Keyword::CurrentTimestamp))
                            .extra("ON UPDATE CURRENT_TIMESTAMP")
                            .not_null(),
                    )
                    // ===== INDEXES =====
                    .index(
                        Index::create()
                            .name("idx_user_version_control_services_user_id")
                            .col(UserVersionControlServices::UserId),
                    )
                    .index(
                        Index::create()
                            .name("idx_user_version_control_services_provider")
                            .col(UserVersionControlServices::VersionControlType),
                    )
                    .index(
                        Index::create()
                            .name("idx_user_version_control_services_provider_username")
                            .col(UserVersionControlServices::VersionControlType)
                            .col(UserVersionControlServices::VersionControlLogin),
                    )
                    .index(
                        Index::create()
                            .name("idx_user_version_control_services_expires_at")
                            .col(UserVersionControlServices::ExpiresAt),
                    )
                    .index(
                        Index::create()
                            .unique()
                            .name("unique_version_control_account")
                            .col(UserVersionControlServices::VersionControlType)
                            .col(UserVersionControlServices::VersionControlUserId),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_user_version_control_services_user")
                            .from(
                                UserVersionControlServices::Table,
                                UserVersionControlServices::UserId,
                            )
                            .to(Users::Table, Users::Id)
                            .on_delete(ForeignKeyAction::Cascade)
                            .on_update(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(UserVersionControlServices::Table)
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}

#[derive(Iden)]
enum UserVersionControlServices {
    Table,
    Id,
    UserId,
    VersionControlType,
    VersionControlUserId,
    VersionControlLogin,
    VersionControlEmail,
    VersionControlAvatarUrl,
    AccessToken,
    RefreshToken,
    TokenType,
    ExpiresAt,
    Scope,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum Users {
    Table,
    #[iden = "id"]
    Id,
}
